### PR TITLE
Make the pcie defer to use a device tree property

### PR DESCRIPTION
**Pull request by mrfixit2001**
This commit supports controlling what mmc nodes get deferred, rather than all of them. Simply append this to the node's device-tree to delay 2000 ms:
  defer_pcie = <2000>;

### CODE REVIEW

**Comment by nuumio** [comment]
Tried this and I'm getting `dwmmc_rockchip: probe of fe310000.dwmmc failed with error -22`. To me it looks like `dw_mci_drv_data.parse_dt` doesn't support deferring like `platform_driver.probe` does and I'd guess it won't work. Tried this on ayufan's bionic minimal image. Or I may be doing something wrong :)

From dmesg:
```
$ dmesg | egrep "dwmmc_rockchip|rockchip-pcie"
[    2.298911] dwmmc_rockchip fe310000.dwmmc: deferring for a max of 2000ms while pcie port initializes. Waited 0ms so far.
[    2.299892] dwmmc_rockchip fe310000.dwmmc: platform data not available
[    2.300578] dwmmc_rockchip: probe of fe310000.dwmmc failed with error -22
[    2.301718] dwmmc_rockchip fe320000.dwmmc: IDMAC supports 32-bit address mode.
[    2.302399] dwmmc_rockchip fe320000.dwmmc: Using internal DMA controller.
[    2.303020] dwmmc_rockchip fe320000.dwmmc: Version ID is 270a
[    2.303577] dwmmc_rockchip fe320000.dwmmc: DW MMC controller at irq 26,32 bit host data width,256 deep fifo
[    2.304522] dwmmc_rockchip fe320000.dwmmc: 'clock-freq-min-max' property was deprecated.
[    2.305262] dwmmc_rockchip fe320000.dwmmc: Looking up vmmc-supply from device tree
[    2.305273] dwmmc_rockchip fe320000.dwmmc: Looking up vmmc-supply property in node /dwmmc@fe320000 failed
[    2.305300] dwmmc_rockchip fe320000.dwmmc: Looking up vqmmc-supply from device tree
[    2.305370] dwmmc_rockchip fe320000.dwmmc: No vmmc regulator found
[    2.305943] dwmmc_rockchip fe320000.dwmmc: GPIO lookup for consumer cd
[    2.305950] dwmmc_rockchip fe320000.dwmmc: using device tree for GPIO lookup
[    2.305978] dwmmc_rockchip fe320000.dwmmc: using lookup tables for GPIO lookup
[    2.305986] dwmmc_rockchip fe320000.dwmmc: lookup for GPIO cd failed
[    2.305995] dwmmc_rockchip fe320000.dwmmc: GPIO lookup for consumer wp
[    2.306002] dwmmc_rockchip fe320000.dwmmc: using device tree for GPIO lookup
[    2.306025] dwmmc_rockchip fe320000.dwmmc: using lookup tables for GPIO lookup
[    2.306032] dwmmc_rockchip fe320000.dwmmc: lookup for GPIO wp failed
[    2.336982] dwmmc_rockchip fe320000.dwmmc: 1 slots initialized
[    2.700323] dwmmc_rockchip fe320000.dwmmc: Successfully tuned phase to 222
[    3.905921] rockchip-pcie f8000000.pcie: GPIO lookup for consumer ep
[    3.905927] rockchip-pcie f8000000.pcie: using device tree for GPIO lookup
[    3.906303] rockchip-pcie f8000000.pcie: Looking up vpcie3v3-supply from device tree
[    3.906471] rockchip-pcie f8000000.pcie: Looking up vpcie1v8-supply from device tree
[    3.906479] rockchip-pcie f8000000.pcie: Looking up vpcie1v8-supply property in node /pcie@f8000000 failed
[    3.906509] rockchip-pcie f8000000.pcie: no vpcie1v8 regulator found
[    3.906515] rockchip-pcie f8000000.pcie: Looking up vpcie0v9-supply from device tree
[    3.906522] rockchip-pcie f8000000.pcie: Looking up vpcie0v9-supply property in node /pcie@f8000000 failed
[    3.906536] rockchip-pcie f8000000.pcie: no vpcie0v9 regulator found
[    3.906659] rockchip-pcie f8000000.pcie: invalid power supply
[    3.924783] rockchip-pcie f8000000.pcie: PCI host bridge to bus 0000:00
```

**Comment by mrfixit2001** [comment]
Hmm that's interesting. It works in my kernel. Did you get the link to the test image in irc? Must be an update to another file which calls the parse_dt routine that allows deferring. Perhaps in a later kernel version. I'm on 4.4.171

**Comment by mrfixit2001** [comment]
I bet it's because my kernel has this commit patched in. Can't confirm because I'm away from my environment but give it a try. 
https://patchwork.kernel.org/patch/9276605/

**Comment by nuumio** [comment]
Did a little fix (removed unneeded include), picked, rearranged some commits and pushed the whole thing: https://github.com/nuumio/linux-kernel/tree/Rp64Sdio0PcieWorkaround

**Pull request closed without merging**
